CREATE TABLE form_tags (
    form_id NUMBER REFERENCES form_data(form_id) ON DELETE CASCADE, 
    tag_id NUMBER REFERENCES tags(tag_id),
    PRIMARY KEY (form_id, tag_id)
);

SELECT * FROM form_tags;

-- Randomized entries for form_tags
INSERT INTO form_tags (form_id, tag_id) VALUES (1, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (1, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (1, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (2, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (2, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (3, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (3, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (4, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (4, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (5, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (5, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (6, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (6, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (7, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (7, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (8, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (8, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (9, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (9, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (10, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (10, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (11, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (11, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (12, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (12, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (13, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (13, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (14, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (14, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (15, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (15, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (16, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (16, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (17, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (17, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (18, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (18, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (19, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (19, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (20, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (20, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (21, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (21, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (22, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (22, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (23, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (23, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (24, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (24, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (25, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (25, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (26, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (26, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (27, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (27, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (28, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (28, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (29, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (29, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (30, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (30, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (31, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (31, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (32, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (32, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (33, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (33, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (34, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (34, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (35, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (35, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (36, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (36, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (37, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (37, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (38, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (38, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (39, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (39, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (40, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (40, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (41, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (41, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (42, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (42, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (43, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (43, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (44, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (44, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (45, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (45, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (46, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (46, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (47, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (47, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (48, 4);
INSERT INTO form_tags (form_id, tag_id) VALUES (48, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (49, 2);
INSERT INTO form_tags (form_id, tag_id) VALUES (49, 10);
INSERT INTO form_tags (form_id, tag_id) VALUES (50, 6);
INSERT INTO form_tags (form_id, tag_id) VALUES (50, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (51, 11);
INSERT INTO form_tags (form_id, tag_id) VALUES (51, 13);
INSERT INTO form_tags (form_id, tag_id) VALUES (52, 3);
INSERT INTO form_tags (form_id, tag_id) VALUES (52, 5);
INSERT INTO form_tags (form_id, tag_id) VALUES (53, 8);
INSERT INTO form_tags (form_id, tag_id) VALUES (53, 9);
INSERT INTO form_tags (form_id, tag_id) VALUES (54, 12);
INSERT INTO form_tags (form_id, tag_id) VALUES (54, 15);
INSERT INTO form_tags (form_id, tag_id) VALUES (55, 7);
INSERT INTO form_tags (form_id, tag_id) VALUES (55, 14);
INSERT INTO form_tags (form_id, tag_id) VALUES (56, 1);
INSERT INTO form_tags (form_id, tag_id) VALUES (56, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (57, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (57, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (58, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (58, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (59, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (59, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (60, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (60, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (61, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (61, 9);
INSERT INTO form_tags(form_id, tag_id) VALUES (62, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (62, 8);
INSERT INTO form_tags(form_id, tag_id) VALUES (63, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (63, 10);
INSERT INTO form_tags(form_id, tag_id) VALUES (64, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (64, 11);
INSERT INTO form_tags(form_id, tag_id) VALUES (65, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (65, 12);
INSERT INTO form_tags(form_id, tag_id) VALUES (66, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (66, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (67, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (67, 8);
INSERT INTO form_tags(form_id, tag_id) VALUES (68, 9);
INSERT INTO form_tags(form_id, tag_id) VALUES (68, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (69, 10);
INSERT INTO form_tags(form_id, tag_id) VALUES (69, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (70, 12);
INSERT INTO form_tags(form_id, tag_id) VALUES (70, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (71, 11);
INSERT INTO form_tags(form_id, tag_id) VALUES (71, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (72, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (72, 8);
INSERT INTO form_tags(form_id, tag_id) VALUES (73, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (73, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (74, 9);
INSERT INTO form_tags(form_id, tag_id) VALUES (74, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (75, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (75, 10);
INSERT INTO form_tags(form_id, tag_id) VALUES (76, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (76, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (77, 8);
INSERT INTO form_tags(form_id, tag_id) VALUES (77, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (78, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (78, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (79, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (79, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (80, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (80, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (81, 9);
INSERT INTO form_tags(form_id, tag_id) VALUES (81, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (82, 10);
INSERT INTO form_tags(form_id, tag_id) VALUES (82, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (83, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (83, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (84, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (84, 11);
INSERT INTO form_tags(form_id, tag_id) VALUES (85, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (85, 12);
INSERT INTO form_tags(form_id, tag_id) VALUES (86, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (86, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (87, 9);
INSERT INTO form_tags(form_id, tag_id) VALUES (87, 8);
INSERT INTO form_tags(form_id, tag_id) VALUES (88, 4);
INSERT INTO form_tags(form_id, tag_id) VALUES (88, 7);
INSERT INTO form_tags(form_id, tag_id) VALUES (89, 1);
INSERT INTO form_tags(form_id, tag_id) VALUES (89, 10);
INSERT INTO form_tags(form_id, tag_id) VALUES (90, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (90, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (91, 2);
INSERT INTO form_tags(form_id, tag_id) VALUES (91, 11);
INSERT INTO form_tags(form_id, tag_id) VALUES (92, 3);
INSERT INTO form_tags(form_id, tag_id) VALUES (92, 5);
INSERT INTO form_tags(form_id, tag_id) VALUES (93, 6);
INSERT INTO form_tags(form_id, tag_id) VALUES (93, 8);
